# SiPM Simulator Default Configuration

# Simulation parameters
simulation:
  n_events: 1  # Number of events to process
  quantum_efficiency: 0.3  # Probability of photon detection (0-1)
  timing_jitter: 0.2  # Gaussian timing uncertainty in ns

# Photon filtering parameters
photon_filter:
  x_range: [-4.25, -3.95]  # SiPM active area x-range in mm
  y_range: [4.32, 4.62]   # SiPM active area y-range in mm
  z_min: 80.0             # Minimum z position for photon detection
  require_core_c: true    # Only process Cherenkov core photons (OP_isCoreC==1)

# Waveform generation
waveform:
  time_window: [-30, 50]  # Total time window for waveform in ns
  time_step: 0.05          # Time sampling in ns
  baseline_range: [-20, -5]  # Time range for noise estimation in ns

# Noise model
noise:
  enable_background: true  # Add Gaussian background noise
  noise_scale: 1.0        # Scale factor for baseline noise level

# Input/Output settings
io:
  sipm_pulse_file: "/fs/ddn/sdf/group/atlas/d/liangyu/dSiPM/fasttiming/SPR_data/SiPM_g2_pulse.root"
  output_dir: "../output"
  save_plots: true        # Save 2D histogram plots
  save_metadata: true     # Save run parameters and statistics
  output_format: "h5"     # Output format: "h5" or "npz"

# ROOT file processing
root_files:
  data_directory: "/fs/ddn/sdf/group/atlas/d/liangyu/dSiPM/single_pions/pi-_E5-5_10000_0"
  file_pattern: "mc_pi-_job_run1_*_Test_20evt_pi-_5_5.root"
  
# Debug and visualization
debug:
  verbose: true
  plot_individual_events: true
  max_photons_per_event: 10000  # Memory protection
